import { ClashDisplay, Satoshi } from '@/fonts';
import "./styles/global.css"
import { State } from './context/context';
import {SideBar, Navigation, Footer} from "./components"

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
   
    <html lang="en">
      <body style={Satoshi.style}>
      <State>
        {children}
      </State> 
         <Footer />
      </body>
    </html>
  )
}
